{
  
  //0-0.3
  file1=new TGraphErrors("C:/root/JetsPbPb010.txt","%lg %lg %lg", "");
 
  file3=new TGraph("C:/root/0-0.3(Updated).txt");
 
  Int_t i;
  
  //first part parameters and errors
  Double_t A=4.22838e+006;
  Double_t B=-5.65242e+000;
  Double_t Aerr=4.89609e+005;
  Double_t Berr=2.50215e-002;
  Double_t A_hi;
  Double_t B_hi;
  Double_t highestValue1;
  Double_t highestValue2;
  // calculating the Sloss
   
   cout<<"Sigma_Sloss(0-0.3)\n\n";
  for(i=0;i<6;i++){
    //Get the yield value of PbPb
    Double_t Pby=file1->GetY()[i];
 //Calculating the possible pTpp values based on parameters from scaled pp spectra
    Double_t Value1=pow((Pby)/(A+Aerr),1/(B));
    Double_t Value2=pow((Pby)/(A-Aerr),1/(B));
    Double_t Value3=pow((Pby)/(A),1/(B+Berr));
    Double_t Value4=pow((Pby)/(A),1/(B-Berr));


    //getting highest value of pTpp out of 4 values above
    A_hi=Value1;
   
    
    B_hi=Value3;
    
    if(A_hi>B_hi){
      highestValue1=A_hi;
    }
    else{
      highestValue1=B_hi;
    }
    //Getting pTAA from a txt file
    Double_t pTAA=file1->GetX()[i];
    //Getting Sloss repect to the parameters generated by scaled pp spectra
    Double_t  Sloss_high1=(highestValue1-pTAA)/(highestValue1);
    
    
   

    
    //Getting stat errors for yield of PbPb
    Double_t Pby_Err=file1->GetEY()[i];

    //Two possible values of pTpp based on +/- the errors of the yield
    Double_t Value5=pow((Pby+Pby_Err)/A,1/B);
    Double_t Value6=pow((Pby-Pby_Err)/A,1/B);

    //pick the highest pTpp value in this case
    if(Value5>Value6){
      highestValue2=Value5;
    }
    else{

      highestValue2=Value6;
    }
    
    //Calculate the highest Sloss resepect to the yield change in AA spectra
    Double_t Sloss_high2=(highestValue2-pTAA)/(highestValue2);    
    
    

    //Getting the Sloss that was calculated before
    Double_t Sloss=file3->GetY()[i];
    //Compute the statistical errors for Sloss
    Double_t Sloss_Err=sqrt(pow((Sloss_high1-Sloss),2)+pow((Sloss_high2-Sloss),2));
    
     
     
    //Getting the pTpp that was calculated before
    Double_t pTpp=file3->GetX()[i];
     
      
      
     
     
     
      
    printf("%lf\t\t\t\t\t%lf\n",pTpp,Sloss_Err);
    
     
     cout<<"\n";
     //For the output pTpp is on the left side and Sloss_Err is on the right side
  }
  
  
  //0.3-0.8
  file5=new TGraphErrors("C:/root/JetsPbPb010(0.3-0.8).txt","%lg %lg %lg","");
 
  file7=new TGraph("C:/root/0.3-0.8(Updated).txt");

  //first part parameters and errors
   A=5.86460e+006;
   B=-5.72970e+000;
   Aerr=4.35352e+005;
   Berr=1.56644e-002;
  
  
 
 
   // calculating the statistical errors of Sloss
  
   cout<<"Sigma_Sloss (0.3-0.8)\n\n";
  
 
  for(Int_t i=0;i<6;i++){
    
   //Get the yield value of PbPb
    Double_t Pby=file5->GetY()[i];
 //Calculating the possible pTpp values based on parameters from scaled pp spectra
    Double_t Value1=pow((Pby)/(A+Aerr),1/(B));
    Double_t Value2=pow((Pby)/(A-Aerr),1/(B));
    Double_t Value3=pow((Pby)/(A),1/(B+Berr));
    Double_t Value4=pow((Pby)/(A),1/(B-Berr));


    //getting highest value of pTpp out of 4 values above
    A_hi=Value1;
   
    
    B_hi=Value3;
    
    if(A_hi>B_hi){
      highestValue1=A_hi;
    }
    else{
      highestValue1=B_hi;
    }
    //Getting pTAA from a txt file
    Double_t pTAA=file5->GetX()[i];
    //Getting Sloss repect to the parameters generated by scaled pp spectra
    Double_t  Sloss_high1=(highestValue1-pTAA)/(highestValue1);
    
    
   

    
    //Getting stat errors for yield of PbPb
    Double_t Pby_Err=file5->GetEY()[i];

    //Two possible values of pTpp based on +/- the errors of the yield
    Double_t Value5=pow((Pby+Pby_Err)/A,1/B);
    Double_t Value6=pow((Pby-Pby_Err)/A,1/B);

    //pick the highest pTpp value in this case
    if(Value5>Value6){
      highestValue2=Value5;
    }
    else{

      highestValue2=Value6;
    }
    
    //Calculate the highest Sloss resepect to the yield change in AA spectra
    Double_t Sloss_high2=(highestValue2-pTAA)/(highestValue2);    
    
    

    //Getting the Sloss that was calculated before
    Double_t Sloss=file7->GetY()[i];
    //Compute the statistical errors for Sloss
    Double_t Sloss_Err=sqrt(pow((Sloss_high1-Sloss),2)+pow((Sloss_high2-Sloss),2));
    
     
     
    //Getting the pTpp that was calculated before
    Double_t pTpp=file7->GetX()[i];
     
      
      
     
     
     
      
    printf("%lf\t\t\t\t\t%lf\n",pTpp,Sloss_Err);
    
     
     cout<<"\n";
    
    
   
     

  }
  
  
  
  

//0.8-1.2
  file8=new TGraphErrors("C:/root/JetsPbPb010(0.8-1.2).txt","%lg %lg %lg", "");
  
  file10=new TGraph("C:/root/0.8-1.2(Updated).txt");

// parameters and errors
  Double_t A=7.52277e+006;
  Double_t B=-5.80903e+000;
  Double_t Aerr=6.85245e+005;
  Double_t Berr=1.92037e-002;
 

  // calculating the statistical errors of Sloss
  
   cout<<"Sigma_Sloss(0.8-1.2)\n\n";

   for(Int_t i=0;i<6;i++){
    
    //Get the yield value of PbPb
    Double_t Pby=file8->GetY()[i];
 //Calculating the possible pTpp values based on parameters from scaled pp spectra
    Double_t Value1=pow((Pby)/(A+Aerr),1/(B));
    Double_t Value2=pow((Pby)/(A-Aerr),1/(B));
    Double_t Value3=pow((Pby)/(A),1/(B+Berr));
    Double_t Value4=pow((Pby)/(A),1/(B-Berr));


    //getting highest value of pTpp out of 4 values above
    A_hi=Value1;
   
    
    B_hi=Value3;
    
    if(A_hi>B_hi){
      highestValue1=A_hi;
    }
    else{
      highestValue1=B_hi;
    }
    //Getting pTAA from a txt file
    Double_t pTAA=file8->GetX()[i];
    //Getting Sloss repect to the parameters generated by scaled pp spectra
    Double_t  Sloss_high1=(highestValue1-pTAA)/(highestValue1);
    
    
   

    
    //Getting stat errors for yield of PbPb
    Double_t Pby_Err=file8->GetEY()[i];

    //Two possible values of pTpp based on +/- the errors of the yield
    Double_t Value5=pow((Pby+Pby_Err)/A,1/B);
    Double_t Value6=pow((Pby-Pby_Err)/A,1/B);

    //pick the highest pTpp value in this case
    if(Value5>Value6){
      highestValue2=Value5;
    }
    else{

      highestValue2=Value6;
    }
    
    //Calculate the highest Sloss resepect to the yield change in AA spectra
    Double_t Sloss_high2=(highestValue2-pTAA)/(highestValue2);    
    
    

    //Getting the Sloss that was calculated before
    Double_t Sloss=file10->GetY()[i];
    //Compute the statistical errors for Sloss
    Double_t Sloss_Err=sqrt(pow((Sloss_high1-Sloss),2)+pow((Sloss_high2-Sloss),2));
    
     
     
    //Getting the pTpp that was calculated before
    Double_t pTpp=file10->GetX()[i];
     
      
      
     
     
     
      
    printf("%lf\t\t\t\t\t%lf\n",pTpp,Sloss_Err);
    
     
     cout<<"\n";
    
  }
  
  //1.2-2.1
  file11=new TGraphErrors("C:/root/JetsPbPb010(1.2-2.1).txt","%lg %lg %lg");
  file12=new TGraph("C:/root/1.2-2.1(Updated).txt");

  // parameters and errors
  Double_t A=2.81502e+007;
  Double_t B=-6.22279e+000;
  Double_t Aerr=1.59600e+006;
  Double_t Berr=1.21346e-002;

  // calculating the statistical errors of Sloss
   
   cout<<"Sigma_Sloss (1.2-2.1)\n\n";

   for(Int_t i=0;i<6;i++){
    //Get the yield value of PbPb
    Double_t Pby=file11->GetY()[i];
 //Calculating the possible pTpp values based on parameters from scaled pp spectra
    Double_t Value1=pow((Pby)/(A+Aerr),1/(B));
    Double_t Value2=pow((Pby)/(A-Aerr),1/(B));
    Double_t Value3=pow((Pby)/(A),1/(B+Berr));
    Double_t Value4=pow((Pby)/(A),1/(B-Berr));


    //getting highest value of pTpp out of 4 values above
    A_hi=Value1;
   
    
    B_hi=Value3;
    
    if(A_hi>B_hi){
      highestValue1=A_hi;
    }
    else{
      highestValue1=B_hi;
    }
    
    //Getting pTAA from a txt file
    Double_t pTAA=file11->GetX()[i];
    //Getting Sloss repect to the parameters generated by scaled pp spectra
    Double_t  Sloss_high1=(highestValue1-pTAA)/(highestValue1);
    
    
   

    
    //Getting stat errors for yield of PbPb
    Double_t Pby_Err=file11->GetEY()[i];

    //Two possible values of pTpp based on +/- the errors of the yield
    Double_t Value5=pow((Pby+Pby_Err)/A,1/B);
    Double_t Value6=pow((Pby-Pby_Err)/A,1/B);

    //pick the highest pTpp value in this case
    if(Value5>Value6){
      highestValue2=Value5;
    }
    else{

      highestValue2=Value6;
    }
    
    //Calculate the highest Sloss resepect to the yield change in AA spectra
    Double_t Sloss_high2=(highestValue2-pTAA)/(highestValue2);    
    
    

    //Getting the Sloss that was calculated before
    Double_t Sloss=file12->GetY()[i];
    //Compute the statistical errors for Sloss
    Double_t Sloss_Err=sqrt(pow((Sloss_high1-Sloss),2)+pow((Sloss_high2-Sloss),2));
    
     
     
    //Getting the pTpp that was calculated before
    Double_t pTpp=file12->GetX()[i];
     
      
      
     
     
     
      
    printf("%lf\t\t\t\t\t%lf\n",pTpp,Sloss_Err);
    
    
     cout<<"\n";
    
   
  }
  
}
